fix: Export AZURE_RESOURCE_GROUP for substitution (#154)
This script is used by KAITO and running the script failed with this
error: `Error: variable ${AZURE_RESOURCE_GROUP} not set`.

This variable also needs to be exported for substitution, as it is
present in `gpu-provisioner-values-template.yaml`.